baseURL = "ACCELERATOR_BASE_URL"
languageCode = "en-US"
defaultContentLanguage = "en"
landingPageURL = "ACCELERATOR_LANDING_PAGE_URL/"


title = "ACCELERATOR_TITLE"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  description = "ACCELERATOR_DESCRIPTION"
  author = "ACCELERATOR_AUTHOR"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  disableSearch = true
  customMermaidURL = "https://unpkg.com/browse/mermaid@8.1.0/dist/mermaid.min.js"
  titleSeparator = "|"
  baseURL = "ACCELERATOR_BASE_URL"
  themeVariant = "custom"


[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "ACCELERATOR_TITLE"
titleSeparator = "|"
weight = 1
languageName = "English"
landingPageName = "Introduction" 
landingPageURL = "ACCELERATOR_LANDING_PAGE_URL/"

[Languages.fr]
title = "Advanced Analytics for Web"
titleSeparator = "|"
weight = 1
languageName = "French"
landingPageName = "Introduction"
landingPageURL = "ACCELERATOR_LANDING_PAGE_URL/"

[[Languages.en.menu.shortcuts]]
name = "Try Snowplow"
identifier = "ts"
url = "https://try.snowplowanalytics.com/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "Book a demo"
identifier = "b"
url = "https://snowplow.io/get-started/book-a-demo-of-snowplow-bdp/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "Documentation"
identifier = "d"
url = "https://docs.snowplow.io/docs/"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github"
identifier = "g"
url = "https://github.com/snowplow"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "Discourse"
identifier = "di"
url = "https://discourse.snowplow.io/"
weight = 50

