name: Run Script

on:
  push:
    branches: [ template/january23-update ]
  pull_request:
    branches: [ template/january23-update ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - run: python scripts/get_versions.py

